### ISSUE TITLE
Треба заставити студентів ходити на пари!

### ISSUE THREAD

**Issue by mr-Serg** [mr-Serg/hello-world#8]
**Сумно** виголошувати лекцію в порожній аудиторії. Лекторові потрібні слухачі та _співвикладачі_ - студент, який ділиться досвідом, вчить усіх, і лектора також!

**Comment by LNUitTutor** [comment]
Лектор і так все знає! Нехай отримує втіху від того, що може сам себе послухати, та ще й отримати за це гроші!

**Comment by mr-Serg** [comment]
Як їх заохотити? - студентів... Можливо, запропонувати до вивчення супер цікавий матеріал?

**Comment by LNUitTutor** [comment]
Ага, платити їм балами (чи цукерками, чи гривнями) за кожне відвідування :) Але на виході з аудиторії, якщо гарно себе поводили

**Comment by mr-Serg** [comment]
Але ж це - хабар! 👎

**Comment by mr-Serg** [comment]
@LNUitTutor ви вже щось придумали?

**Comment by mr-Serg** [comment]
@LNUitTutor  повторюю запитання

**Comment by LNUitTutor** [comment]
@mr-Serg Я отримав повідомлення-нагадування

**Comment by mr-Serg** [comment]
Ще одна спроба відправити повідомлення
/cc @LNUitTutor

**Comment by LNUitTutor** [comment]
Перевірка project automation

**Comment by mr-Serg** [comment]
Дивимося на реакцію проекту

**Comment by mr-Serg** [comment]
Реагує!
