### ISSUE TITLE
Треба написати конспект чергової лекції

### ISSUE THREAD

**Issue by mr-Serg** [mr-Serg/hello-world#9]
Завдання для Лекції 4

**Comment by mr-Serg** [comment]
Чи готовий вже конспект, @LNUitTutor ?

**Comment by LNUitTutor** [comment]
Прошу не заважати

**Comment by LNUitTutor** [comment]
Це завдання пов'язане з #8

**Comment by LNUitTutor** [comment]
@mr-Serg перевірте повідомлення

**Comment by LNUitTutor** [comment]
Project automation in action!

**Comment by mr-Serg** [comment]
Спостерігаємо і за цим

**Comment by mr-Serg** [comment]
Все працює
